<?php
/**
 * Created by Josh.
 * Date: 9/3/2018
 * Time: 10:56 AM
 */

require_once(_PS_MODULE_DIR_ . "dashnews/classes/CategoryNews.php");


class AdminCategoryNewsController extends AdminController
{

    public function __construct()
    {
        $this->bootstrap = true;
        $this->table = 'categorynews';
        $this->className = "CategoryNews";
        $this->lang = true;

        $this->explicitSelect = true;
        $this->allow_export = true;

        parent::__construct();


        $this->addRowAction('edit');
        $this->addRowAction('delete');

        $this->bulk_actions = array(
            'delete' => array(
                'text' => $this->l('Delete selected'),
                'confirm' => $this->l('Delete selected items?')
            )
        );

        $this->setFieldsList();
    }

    private function setFieldsList()
    {
        $this->fields_list = array(
            'id_categorynews' => array(
                'title' => $this->l('id'),
                'align' => 'center',
                'width' => 25
            ),
            'title' => array(
                'title' => $this->l('Title'),
                'width' => 'auto',
            ),
            'description' => array(
                'title' => $this->l('Description'),
                'width' => 'auto',
            ),
            'active' => array(
                'title' => $this->l('Status'),
                'width' => 'auto',
                'active' => 'status',
                'align' => 'center',
                'type' => 'bool',
                'orderby' => false
            )
        );
    }

    public function renderForm()
    {
        $this->fields_form =
            array(
                'legend' => array(
                    'title' => $this->trans('Category', array(), 'Admin.News.Feature'),
                    'icon' => 'icon-cogs'
                ),
                'input' => array(
                    array( //title
                        'type' => 'hidden',
                        'name' => 'id_categorynews',
                    ),
                    array( //title
                        'type' => 'text',
                        'label' => $this->l('Title'),
                        'name' => 'title',
                        'lang' => 'true',
                        'class' => 'lg',
                        'required' => true,
                        'desc' => $this->l('Please enter title')
                    ),
                    array( //description
                        'type' => 'textarea',
                        'label' => $this->l('Description'),
                        'name' => 'description',
                        'class' => 'lg',
                        'lang' => 'true',
                        'autoload_rte' => 'rte'
                    ), // upload an image
                ),
                'submit' => array(
                    'title' => $this->trans('Save', array(), 'Admin.Actions'),
                    'name' => 'submit-news-category'
                )
            );

        return parent::renderForm();
    }

    public function initPageHeaderToolbar()
    {
        parent::initPageHeaderToolbar(); // TODO: Change the autogenerated stub
        if (empty($this->display)) {
            $this->page_header_toolbar_btn['new_category'] = array(
                'href' => self::$currentIndex . '&addcategorynews&token=' . $this->token,
                'desc' => $this->trans('Add category', array(), "Admin.CategoryNews.Create"),
                'icon' => 'process-icon-new'
            );
        }
    }


}