<?php
/**
 * Created by Josh.
 * Date: 8/28/2018
 * Time: 3:45 PM
 */


require_once(_PS_MODULE_DIR_ . "dashnews/classes/News.php");
require_once(_PS_MODULE_DIR_ . "dashnews/classes/CategoryNews.php");

/**
 * @property News $object
 */
class AdminNewsController extends AdminController
{
    /**
     * AdminNewsController constructor.
     */
    public function __construct()
    {
        $this->bootstrap = true;
        $this->table = 'news';
        $this->className = "News";
        $this->lang = true;

        $this->explicitSelect = true;
        $this->allow_export = true;

        parent::__construct();


        $this->addRowAction('edit');
        $this->addRowAction('delete');

        $this->bulk_actions = array(
            'delete' => array(
                'text' => $this->l('Delete selected'),
                'confirm' => $this->l('Delete selected items?')
            )
        );


        $this->setFieldsList();

    }

    private function setFieldsList()
    {
        $this->fields_list = array(
            'id_news' => array(
                'title' => $this->l('id'),
                'align' => 'center',
                'width' => 25
            ),
            'description' => array(
                'title' => $this->l('Description'),
                'width' => 'auto',
            ),
            'title' => array(
                'title' => $this->l('Title'),
                'width' => 'auto',
            ),
            'date_from' => array(
                'title' => $this->l('Date from'),
                'width' => 'auto',
            ),
            'date_to' => array(
                'title' => $this->l('Date to'),
                'width' => 'auto',
            ),
            'active' => array(
                'title' => $this->l('Status'),
                'width' => 'auto',
                'active' => 'status',
                'align' => 'center',
                'type' => 'bool',
                'orderby' => false
            )

        );
    }

    public function setMedia()
    {
        parent::setMedia();
    }

    public function initPageHeaderToolbar()
    {
        parent::initPageHeaderToolbar(); // TODO: Change the autogenerated stub
        if (empty($this->display)) {
            $this->page_header_toolbar_btn['new_news'] = array(
                'href' => self::$currentIndex . '&addnews&token=' . $this->token,
                'desc' => $this->trans('Add news', array(), "Admin.News.Create"),
                'icon' => 'process-icon-new'
            );
        }
    }

    public function renderForm()
    {

        if (!($obj = $this->loadObject(true))) {
            return;
        }

        $image_url = "<img src='{$this->getImageUrl($obj)}' class='imgm' height='200px' width='200px'> ";

        $categories = CategoryNews::getAll();

        $this->fields_form =
            array(
                'legend' => array(
                    'title' => $this->trans('Create', array(), 'Admin.News.Feature'),
                    'icon' => 'icon-cogs'
                ),
                'input' => array(
                    array( //title
                        'type' => 'hidden',
                        'name' => 'id_news',
                    ),
                    array( //title
                        'type' => 'text',
                        'label' => $this->l('Title'),
                        'name' => 'title',
                        'lang' => 'true',
                        'class' => 'lg',
                        'required' => true,
                        'desc' => $this->l('Please enter title')
                    ),
                    array( //description
                        'type' => 'textarea',
                        'label' => $this->l('Description'),
                        'name' => 'description',
                        'class' => 'lg',
                        'lang' => 'true',
                        'autoload_rte' => 'rte'
                    ),
                    array( //date from
                        'type' => 'date',
                        'label' => $this->l('Date from'),
                        'name' => 'date_from'
                    ),
                    array( //description
                        'type' => 'date',
                        'label' => $this->l('Date to'),
                        'name' => 'date_to'
                    ),
                    array(
                        'type' => 'select',
                        'label' => $this->l('Categories'),
                        'name' => 'categories[]',
                        'multiple' => true,
                        'options' => array(
                            'query' => $categories,
                            'id' => 'id_categorynews',
                            'name' => 'description'
                        ),
                    ),
                    array(
                        'type' => 'file',
                        'label' => 'Upload image',
                        'name' => 'image',
                        'image' => $image_url,
                        'height' => 50,
                        'weight' => 50,
                        'display_image' => true,
                        'required' => true
                    )
                ),
                'submit' => array(
                    'title' => $this->trans('Save', array(), 'Admin.Actions'),
                    'name' => 'submit-news'
                )
            );

        if (isset($obj->id_news)) {
            $this->fields_value['categories[]'] = $obj->getCategories();
        }

        return parent::renderForm();
    }

    private function getImageUrl($obj)
    {
        $defaultUrl = "../modules/dashnews/default.jpg";
        $url = "../img/dashnews/";
        if ($obj->image == null) {
            $image = $defaultUrl;
        } else {
            $image = ($obj->image !== '') ? ($url . $obj->image) : $defaultUrl;
        }
        return $image;
    }

    public function postProcess()
    {
        //check if date_from is less than date_to
        $ok = $this->validateInputDates();
        if (!$ok) {
            return;
        }

        $imageName = '';
        if ($obj = $this->loadObject(true)) {
            $imageName = $obj->image;
        }

        parent::postProcess();

        if (empty($this->errors)) {
            if (Tools::isSubmit('submit-news')) {
                $this->updateNewsImage($imageName);

                $this->updateNewsCategories();
            }
        }
    }

    /**
     * @return bool
     */
    private function validateInputDates()
    {
        if (Tools::isSubmit('submit-news')) {
            if (Tools::getValue('date_from') && Tools::getValue('date_to')) {
                $dateFrom = Tools::getValue('date_from');
                $dateTo = Tools::getValue('date_to');

                $dateTimestampFrom = strtotime($dateFrom);
                $dateTimestampTo = strtotime($dateTo);

                if ($dateTimestampFrom > $dateTimestampTo) {
                    return false;
                }
            }
        }
        return true;
    }

    /**
     * @param $imageName
     * @return array
     */
    private function updateNewsImage($imageName)
    {
        $db = Db::getInstance();
        $dir = $this->getImagesDir();
        $id = Tools::getValue('id_news');

        if ($_FILES['image']['name'] !== '') {
            $fileName = News::uploadImg($id, $dir, 'image');

            $db->update('news', array('image' => $fileName), 'id_news=' . $id);
        } else {
            $db->update('news', array('image' => $imageName), 'id_news=' . $id);
        }
        return array($db, $id);
    }

    private function getImagesDir()
    {
        return _PS_IMG_DIR_ . "dashnews";
    }

    private function updateNewsCategories()
    {
        $db = Db::getInstance();
        $id = Tools::getValue('id_news');
        $db->delete('news_categorynews', 'id_news=' . $id);

        if (Tools::getValue('categories')) {
            $categories = Tools::getValue('categories');

            foreach ($categories as $k => $categoryId) {
                $db->insert('news_categorynews', array('id_categorynews' => $categoryId, 'id_news' => $id));
            }
        }
    }
}
